# This rule is not used by the project openapi-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the operator.anyflow.net.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openapi-operator
    app.kubernetes.io/managed-by: kustomize
  name: openapiservice-editor-role
rules:
  - apiGroups:
      - operator.anyflow.net
    resources:
      - openapiservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.anyflow.net
    resources:
      - openapiservices/status
    verbs:
      - get
