---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - extensions.istio.io
  resources:
  - wasmplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.anyflow.net
  resources:
  - openapiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.anyflow.net
  resources:
  - openapiservices/finalizers
  verbs:
  - update
- apiGroups:
  - operator.anyflow.net
  resources:
  - openapiservices/status
  verbs:
  - get
  - patch
  - update
